name = "rpgm-press-blog"
compatibility_date = "2026-08-29"
account_id = "bb37de82a8d1040e9945ead5a03bab8d"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[[routes]]
pattern = "blog.rpgm.tools"
custom_domain = true
