name = "rpgm-press-blog"
compatibility_date = "2026-08-29"
# account_id = "TODO - confirm rpgm.tools zone's account before first deploy"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[[routes]]
pattern = "blog.rpgm.tools"
custom_domain = true
